galaxy_info:
  author: Andrs12
  description: Update packages, install common packages and configure webadmin user and SSH settings.
  company: Andrs12
  license: GPL-2.0-or-later
  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - 8
        - 9
        
  galaxy_tags:
    - system
    - common
    - setup

dependencies: []