---
- name: restart nginx
  shell: nginx -s reload || service nginx restart || /etc/init.d/nginx restart
  ignore_errors: yes

- name: restart apache
  service:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: restarted
  ignore_errors: yes
