---
- name: reload webserver
  shell: |
    if [ "{{ webserver_type }}" = "nginx" ]; then
      nginx -s reload || service nginx reload || /etc/init.d/nginx reload
    else
      service {{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }} reload
    fi
  ignore_errors: yes
