---
- name: reload webserver
  service:
    name: "{{ webserver_service_name }}"
    state: reloaded
  vars:
    webserver_service_name: "{{ 'nginx' if webserver_type == 'nginx' else ('apache2' if ansible_os_family == 'Debian' else 'httpd') }}"
