---
galaxy_info:
  author: Andrs12
  description: Deploy static website content
  company: Andrs12
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - web
    - deployment
    - static

dependencies: []
