---
- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow configured services
  community.general.ufw:
    rule: allow
    name: "{{ item }}"
  loop: "{{ firewall_allowed_services }}"

- name: Allow configured custom ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ firewall_allowed_ports }}"
  when: firewall_allowed_ports | length > 0

- name: Enable UFW with default policy
  community.general.ufw:
    state: enabled
    policy: "{{ firewall_default_policy }}"
