---
- name: Install Apache (Debian/Ubuntu)
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Apache (RedHat/CentOS)
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Create document root directory
  file:
    path: "{{ webserver_document_root }}"
    state: directory
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"
    mode: '0755'

- name: Deploy Apache VirtualHost (Debian/Ubuntu)
  template:
    src: apache_vhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "Debian"
  notify: restart apache

- name: Deploy Apache VirtualHost (RedHat/CentOS)
  template:
    src: apache_vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat"
  notify: restart apache

- name: Ensure Apache is started and enabled (Debian/Ubuntu)
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Ensure Apache is started and enabled (RedHat/CentOS)
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"
